---
title: "Template for UNSW-themed Quarto slides"
author: Dr Patrick Laub
format:
  html:
    theme: materia
---

This is a template for using [Quarto](http://quarto.org) to create [reveal.js](http://revealjs.com) HTML slides according to a UNSW theme.
Here are the generated slides in [HTML format](template.html) and in [PDF format](template.pdf).

To start a new set of slides, install Quarto and run

```bash
quarto use template Pat-Laub/UNSW-Quarto-Slides-Template
```

in an empty directory; this downloads just the template files you need.
Alternatively, you can clone the [Github repository](https://github.com/Pat-Laub/UNSW-Quarto-Slides-Template).
I used these tools to make the [lecture slides for ACTL3143 & ACTL5111](http://pat-laub.github.io/DeepLearningForActuaries/), a deep learning course for actuaries.

To render the main [template.qmd](https://github.com/Pat-Laub/UNSW-Quarto-Slides-Template/blob/main/template.qmd) file, run `quarto render template.qmd` on the commandline, or use the Render button in [RStudio](http://rstudio.com) or VS Code (with the Quarto extension).

For a detailed setup/explainer of how I use Quarto for lecture materials, check out the following screencast I made:

{{< video https://youtu.be/41yTFhQBXaE >}}

::: {.callout-note}
Reveal.js slides can be progressed by pressing the spacebar key, or by clicking on the arrows at the edge of the slide.
:::

::: {.callout-warning}
Quarto creates HTML slides, and converting these to PDF is slightly clunky.
I use the [decktape](https://github.com/astefanutti/decktape) tool, calling `decktape template.html template.pdf`, to create [PDF slides](template.pdf).
This normally works well, though all interactivity in the HTML will be discarded.
:::
